// Code generated by "genprotocol -ver=1.0 -prefix=c2s -basedir example -statstype=int"

package c2s_authorize

import (
	"bytes"
	"fmt"

	"github.com/kasworld/genprotocol/example/c2s_idcmd"
)

type AuthorizedCmds [c2s_idcmd.CommandID_Count]bool

func (acidl *AuthorizedCmds) String() string {
	var buff bytes.Buffer
	fmt.Fprintf(&buff, "AuthorizedCmds[")
	for i, v := range acidl {
		if v {
			fmt.Fprintf(&buff, "%v ", c2s_idcmd.CommandID(i))
		}
	}
	fmt.Fprintf(&buff, "]")
	return buff.String()
}

func NewAllSet() *AuthorizedCmds {
	rtn := new(AuthorizedCmds)
	for i := 0; i < c2s_idcmd.CommandID_Count; i++ {
		rtn[i] = true
	}
	return rtn
}

func NewByCmdIDList(cmdlist []c2s_idcmd.CommandID) *AuthorizedCmds {
	rtn := new(AuthorizedCmds)
	for _, id := range cmdlist {
		rtn[id] = true
	}
	return rtn
}

func (acidl *AuthorizedCmds) Union(src *AuthorizedCmds) *AuthorizedCmds {
	for cmdid, auth := range src {
		if auth {
			acidl[cmdid] = true
		}
	}
	return acidl
}

func (acidl *AuthorizedCmds) SubIntersection(src *AuthorizedCmds) *AuthorizedCmds {
	for cmdid, auth := range src {
		if auth {
			acidl[cmdid] = false
		}
	}
	return acidl
}

func (acidl *AuthorizedCmds) Duplicate() *AuthorizedCmds {
	rtn := *acidl
	return &rtn
}

func (acidl *AuthorizedCmds) CheckAuth(cmdid c2s_idcmd.CommandID) bool {
	return acidl[cmdid]
}
