// Code generated by "genprotocol -ver=1.0 -prefix=c2s -basedir example -statstype=int"

package c2s_obj

/* protocol template

type ReqInvalidCmd_data struct {
	Dummy uint8
}
type RspInvalidCmd_data struct {
	Dummy uint8
}

type ReqLogin_data struct {
	Dummy uint8
}
type RspLogin_data struct {
	Dummy uint8
}

type ReqHeartbeat_data struct {
	Dummy uint8
}
type RspHeartbeat_data struct {
	Dummy uint8
}

type ReqChat_data struct {
	Dummy uint8
}
type RspChat_data struct {
	Dummy uint8
}

type NotiBroadcast_data struct {
	Dummy uint8
}

*/
