// Code generated by "genprotocol -ver=1.0 -prefix=c2s -basedir example -statstype=int"

package c2s_obj

/* protocol template

// InvalidCmd not used
type ReqInvalidCmd_data struct {
	Dummy uint8 // change as you need
}
// InvalidCmd not used
type RspInvalidCmd_data struct {
	Dummy uint8 // change as you need
}

// Login make session with nickname and enter stage
type ReqLogin_data struct {
	Dummy uint8 // change as you need
}
// Login make session with nickname and enter stage
type RspLogin_data struct {
	Dummy uint8 // change as you need
}

// Heartbeat prevent connection timeout
type ReqHeartbeat_data struct {
	Dummy uint8 // change as you need
}
// Heartbeat prevent connection timeout
type RspHeartbeat_data struct {
	Dummy uint8 // change as you need
}

// Chat chat to stage
type ReqChat_data struct {
	Dummy uint8 // change as you need
}
// Chat chat to stage
type RspChat_data struct {
	Dummy uint8 // change as you need
}

// Act send user action
type ReqAct_data struct {
	Dummy uint8 // change as you need
}
// Act send user action
type RspAct_data struct {
	Dummy uint8 // change as you need
}

// Broadcast send message to all connection
type NotiBroadcast_data struct {
	Dummy uint8 // change as you need
}

*/
