// Code generated by "genprotocol -ver=1.0 -prefix=c2s -basedir example -statstype=int"

package c2s_error

import "fmt"

type ErrorCode uint16 // use in packet header, DO NOT CHANGE
const (
	None             ErrorCode = iota // no error
	InvalidDirection                  // direction not valid
	ActionProhibited                  // cannot act
	ObjectNotFound                    // object not found
	ActionChaned                      // server change action
	ActionCanceled                    // server cancel action

	ErrorCode_Count int = iota
)

var _ErrorCode2string = [ErrorCode_Count][2]string{
	None:             {"None", "no error"},
	InvalidDirection: {"InvalidDirection", "direction not valid"},
	ActionProhibited: {"ActionProhibited", "cannot act"},
	ObjectNotFound:   {"ObjectNotFound", "object not found"},
	ActionChaned:     {"ActionChaned", "server change action"},
	ActionCanceled:   {"ActionCanceled", "server cancel action"},
}

func (e ErrorCode) String() string {
	if e >= 0 && e < ErrorCode(ErrorCode_Count) {
		return _ErrorCode2string[e][0]
	}
	return fmt.Sprintf("ErrorCode%d", uint16(e))
}
func (e ErrorCode) CommentString() string {
	if e >= 0 && e < ErrorCode(ErrorCode_Count) {
		return _ErrorCode2string[e][1]
	}
	return ""
}

// implement error interface
func (e ErrorCode) Error() string {
	return "c2s_error." + e.String()
}

var _string2ErrorCode = map[string]ErrorCode{
	"None":             None,
	"InvalidDirection": InvalidDirection,
	"ActionProhibited": ActionProhibited,
	"ObjectNotFound":   ObjectNotFound,
	"ActionChaned":     ActionChaned,
	"ActionCanceled":   ActionCanceled,
}

func String2ErrorCode(s string) (ErrorCode, bool) {
	v, b := _string2ErrorCode[s]
	return v, b
}
