// Code generated by "genprotocol -ver=1.0 -prefix=c2s -basedir example -statstype=int"

package c2s_handlereq

/* obj base demux fn map template
	var DemuxReq2ObjAPIFnMap = [...]func(
		me interface{}, hd c2s_packet.Header, robj interface{}) (
		c2s_packet.Header, interface{}, error){
	c2s_idcmd.InvalidCmd: Req2ObjAPI_InvalidCmd,
c2s_idcmd.Login: Req2ObjAPI_Login,
c2s_idcmd.Heartbeat: Req2ObjAPI_Heartbeat,
c2s_idcmd.Chat: Req2ObjAPI_Chat,

}   // DemuxReq2ObjAPIFnMap

	func Req2ObjAPI_InvalidCmd(
		me interface{}, hd c2s_packet.Header, robj interface{}) (
		c2s_packet.Header, interface{},  error) {
		req, ok := robj.(*c2s_obj.ReqInvalidCmd_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqInvalidCmd(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqInvalidCmd(
		me interface{}, hd c2s_packet.Header, robj *c2s_obj.ReqInvalidCmd_data) (
		c2s_packet.Header, *c2s_obj.RspInvalidCmd_data, error) {
		sendHeader := c2s_packet.Header{
			ErrorCode : c2s_error.None,
		}
		sendBody := &c2s_obj.RspInvalidCmd_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_Login(
		me interface{}, hd c2s_packet.Header, robj interface{}) (
		c2s_packet.Header, interface{},  error) {
		req, ok := robj.(*c2s_obj.ReqLogin_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqLogin(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqLogin(
		me interface{}, hd c2s_packet.Header, robj *c2s_obj.ReqLogin_data) (
		c2s_packet.Header, *c2s_obj.RspLogin_data, error) {
		sendHeader := c2s_packet.Header{
			ErrorCode : c2s_error.None,
		}
		sendBody := &c2s_obj.RspLogin_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_Heartbeat(
		me interface{}, hd c2s_packet.Header, robj interface{}) (
		c2s_packet.Header, interface{},  error) {
		req, ok := robj.(*c2s_obj.ReqHeartbeat_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqHeartbeat(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqHeartbeat(
		me interface{}, hd c2s_packet.Header, robj *c2s_obj.ReqHeartbeat_data) (
		c2s_packet.Header, *c2s_obj.RspHeartbeat_data, error) {
		sendHeader := c2s_packet.Header{
			ErrorCode : c2s_error.None,
		}
		sendBody := &c2s_obj.RspHeartbeat_data{
		}
		return sendHeader, sendBody, nil
	}

	func Req2ObjAPI_Chat(
		me interface{}, hd c2s_packet.Header, robj interface{}) (
		c2s_packet.Header, interface{},  error) {
		req, ok := robj.(*c2s_obj.ReqChat_data)
		if !ok {
			return hd, nil, fmt.Errorf("Packet type miss match %v", robj)
		}
		rhd, rsp, err := objAPIFn_ReqChat(me, hd, req)
		return rhd, rsp, err
	}
	func objAPIFn_ReqChat(
		me interface{}, hd c2s_packet.Header, robj *c2s_obj.ReqChat_data) (
		c2s_packet.Header, *c2s_obj.RspChat_data, error) {
		sendHeader := c2s_packet.Header{
			ErrorCode : c2s_error.None,
		}
		sendBody := &c2s_obj.RspChat_data{
		}
		return sendHeader, sendBody, nil
	}

*/
