// Code generated by "genprotocol -ver=1.0 -prefix=c2s -basedir example -statstype=int"

package c2s_idnoti

import "fmt"

type NotiID uint16 // use in packet header, DO NOT CHANGE
const (
	Broadcast NotiID = iota //

	NotiID_Count int = iota
)

var _NotiID2string = [NotiID_Count][2]string{
	Broadcast: {"Broadcast", ""},
}

func (e NotiID) String() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e][0]
	}
	return fmt.Sprintf("NotiID%d", uint16(e))
}
func (e NotiID) CommentString() string {
	if e >= 0 && e < NotiID(NotiID_Count) {
		return _NotiID2string[e][1]
	}
	return ""
}

var _string2NotiID = map[string]NotiID{
	"Broadcast": Broadcast,
}

func String2NotiID(s string) (NotiID, bool) {
	v, b := _string2NotiID[s]
	return v, b
}
