// Code generated by "genprotocol.exe -ver=1.0 -prefix=c2s -basedir=example -statstype=int"

package c2s_gob

import (
	"bytes"
	"encoding/gob"
	"fmt"

	"github.com/kasworld/genprotocol/example/c2s_idcmd"
	"github.com/kasworld/genprotocol/example/c2s_idnoti"
	"github.com/kasworld/genprotocol/example/c2s_obj"
	"github.com/kasworld/genprotocol/example/c2s_packet"
)

// marshal body and append to oldBufferToAppend
// and return newbuffer, body type, error
func MarshalBodyFn(body interface{}, oldBuffToAppend []byte) ([]byte, byte, error) {
	network := bytes.NewBuffer(oldBuffToAppend)
	enc := gob.NewEncoder(network)
	err := enc.Encode(body)
	return network.Bytes(), 0, err
}

func UnmarshalPacket(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	switch h.FlowType {
	case c2s_packet.Request:
		if int(h.Cmd) >= len(ReqUnmarshalMap) {
			return nil, fmt.Errorf("unknown request command: %v %v",
				h.FlowType, c2s_idcmd.CommandID(h.Cmd))
		}
		return ReqUnmarshalMap[h.Cmd](h, bodyData)

	case c2s_packet.Response:
		if int(h.Cmd) >= len(RspUnmarshalMap) {
			return nil, fmt.Errorf("unknown response command: %v %v",
				h.FlowType, c2s_idcmd.CommandID(h.Cmd))
		}
		return RspUnmarshalMap[h.Cmd](h, bodyData)

	case c2s_packet.Notification:
		if int(h.Cmd) >= len(NotiUnmarshalMap) {
			return nil, fmt.Errorf("unknown notification command: %v %v",
				h.FlowType, c2s_idcmd.CommandID(h.Cmd))
		}
		return NotiUnmarshalMap[h.Cmd](h, bodyData)
	}
	return nil, fmt.Errorf("unknown packet FlowType %v", h.FlowType)
}

var ReqUnmarshalMap = [...]func(h c2s_packet.Header, bodyData []byte) (interface{}, error){
	c2s_idcmd.InvalidCmd: Unmarshal_ReqInvalidCmd,
	c2s_idcmd.Login:      Unmarshal_ReqLogin,
	c2s_idcmd.Heartbeat:  Unmarshal_ReqHeartbeat,
	c2s_idcmd.Chat:       Unmarshal_ReqChat,
	c2s_idcmd.Act:        Unmarshal_ReqAct,
}

var RspUnmarshalMap = [...]func(h c2s_packet.Header, bodyData []byte) (interface{}, error){
	c2s_idcmd.InvalidCmd: Unmarshal_RspInvalidCmd,
	c2s_idcmd.Login:      Unmarshal_RspLogin,
	c2s_idcmd.Heartbeat:  Unmarshal_RspHeartbeat,
	c2s_idcmd.Chat:       Unmarshal_RspChat,
	c2s_idcmd.Act:        Unmarshal_RspAct,
}

var NotiUnmarshalMap = [...]func(h c2s_packet.Header, bodyData []byte) (interface{}, error){
	c2s_idnoti.Broadcast: Unmarshal_NotiBroadcast,
}

func Unmarshal_ReqInvalidCmd(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.ReqInvalidCmd_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_RspInvalidCmd(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.RspInvalidCmd_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_ReqLogin(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.ReqLogin_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_RspLogin(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.RspLogin_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_ReqHeartbeat(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.ReqHeartbeat_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_RspHeartbeat(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.RspHeartbeat_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_ReqChat(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.ReqChat_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_RspChat(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.RspChat_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_ReqAct(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.ReqAct_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_RspAct(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.RspAct_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}

func Unmarshal_NotiBroadcast(h c2s_packet.Header, bodyData []byte) (interface{}, error) {
	var args c2s_obj.NotiBroadcast_data
	network := bytes.NewBuffer(bodyData)
	dec := gob.NewDecoder(network)
	err := dec.Decode(&args)
	return &args, err
}
